# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.srcs/sources_1/ip/block_sprite/block_sprite.xci
# IP: The module: 'block_sprite' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.gen/sources_1/ip/block_sprite/block_sprite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_sprite'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.srcs/sources_1/ip/block_sprite/block_sprite.xci
# IP: The module: 'block_sprite' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.gen/sources_1/ip/block_sprite/block_sprite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_sprite'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
