# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.srcs/sources_1/ip/pillar_rom_gen/pillar_rom_gen.xci
# IP: The module: 'pillar_rom_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.gen/sources_1/ip/pillar_rom_gen/pillar_rom_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pillar_rom_gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.srcs/sources_1/ip/pillar_rom_gen/pillar_rom_gen.xci
# IP: The module: 'pillar_rom_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.gen/sources_1/ip/pillar_rom_gen/pillar_rom_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pillar_rom_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
