set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN L1 [get_ports {led[3]}]
set_property PACKAGE_PIN P1 [get_ports {led[2]}]
set_property PACKAGE_PIN N3 [get_ports {led[1]}]
set_property PACKAGE_PIN P3 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports data]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN B17 [get_ports data]


set_property IOSTANDARD LVCMOS33 [get_ports kclk]
set_property PACKAGE_PIN C17 [get_ports kclk]

set_property IOSTANDARD LVCMOS33 [get_ports {scancode_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scancode_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scancode_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scancode_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scancode_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scancode_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scancode_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scancode_led[0]}]
set_property PACKAGE_PIN U16 [get_ports {scancode_led[0]}]
set_property PACKAGE_PIN E19 [get_ports {scancode_led[1]}]
set_property PACKAGE_PIN U19 [get_ports {scancode_led[2]}]
set_property PACKAGE_PIN V19 [get_ports {scancode_led[3]}]
set_property PACKAGE_PIN W18 [get_ports {scancode_led[4]}]
set_property PACKAGE_PIN U15 [get_ports {scancode_led[5]}]
set_property PACKAGE_PIN U14 [get_ports {scancode_led[6]}]
set_property PACKAGE_PIN V14 [get_ports {scancode_led[7]}]
