# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.srcs/sources_1/ip/bomb_rom/bomb_rom.xci
# IP: The module: 'bomb_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.gen/sources_1/ip/bomb_rom/bomb_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bomb_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.srcs/sources_1/ip/bomb_rom/bomb_rom.xci
# IP: The module: 'bomb_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youssef/Desktop/DigitalSystems/Bomberman/Bomberman.gen/sources_1/ip/bomb_rom/bomb_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bomb_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
