set_property SRC_FILE_INFO {cfile:C:/Users/youssef/Desktop/DigitalSystems/Exp7/Exp7.srcs/constrs_1/new/Source.xdc rfile:../../../Exp7.srcs/constrs_1/new/Source.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports A]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports B]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports OUT]
